# DO NOT EDIT THIS FILE!
#
# Python module WhatsTheWord.game_logic generated by omniidl

import omniORB
omniORB.updateModule("WhatsTheWord.game_logic")

# ** 1. Stub files contributing to this module
import WhatsTheWord_idl

# ** 2. Sub-modules

# ** 3. End
