# DO NOT EDIT THIS FILE!
#
# Python module WhatsTheWord generated by omniidl

import omniORB
omniORB.updateModule("WhatsTheWord")

# ** 1. Stub files contributing to this module
import WhatsTheWord_idl

# ** 2. Sub-modules
from . import client
from . import game_logic
from . import referenceClasses

# ** 3. End
