# DO NOT EDIT THIS FILE!
#
# Python module WhatsTheWord__POA.client generated by omniidl

import omniORB
omniORB.updateModule("WhatsTheWord__POA.client")

# ** 1. Stub files contributing to this module
import WhatsTheWord_idl

# ** 2. Sub-modules
from . import admin
from . import player

# ** 3. End
