# DO NOT EDIT THIS FILE!
#
# Python module WhatsTheWord__POA.client.player generated by omniidl

import omniORB
omniORB.updateModule("WhatsTheWord__POA.client.player")

# ** 1. Stub files contributing to this module
import WhatsTheWord_idl

# ** 2. Sub-modules

# ** 3. End
