# Python stubs generated by omniidl from WhatsTheWord.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "WhatsTheWord"
#
__name__ = "WhatsTheWord"
_0_WhatsTheWord = omniORB.openModule("WhatsTheWord", r"WhatsTheWord.idl")
_0_WhatsTheWord__POA = omniORB.openModule("WhatsTheWord__POA", r"WhatsTheWord.idl")


#
# Start of module "WhatsTheWord.referenceClasses"
#
__name__ = "WhatsTheWord.referenceClasses"
_0_WhatsTheWord.referenceClasses = omniORB.openModule("WhatsTheWord.referenceClasses", r"WhatsTheWord.idl")
_0_WhatsTheWord__POA.referenceClasses = omniORB.openModule("WhatsTheWord__POA.referenceClasses", r"WhatsTheWord.idl")


# struct ValuesList
_0_WhatsTheWord.referenceClasses.ValuesList = omniORB.newEmptyClass()
class ValuesList (omniORB.StructBase):
    _NP_RepositoryId = "IDL:WhatsTheWord/referenceClasses/ValuesList:1.0"

    def __init__(self, values):
        self.values = values

_0_WhatsTheWord.referenceClasses.ValuesList = ValuesList
_0_WhatsTheWord.referenceClasses._d_ValuesList  = (omniORB.tcInternal.tv_struct, ValuesList, ValuesList._NP_RepositoryId, "ValuesList", "values", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_any, 0))
_0_WhatsTheWord.referenceClasses._tc_ValuesList = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.referenceClasses._d_ValuesList)
omniORB.registerType(ValuesList._NP_RepositoryId, _0_WhatsTheWord.referenceClasses._d_ValuesList, _0_WhatsTheWord.referenceClasses._tc_ValuesList)
del ValuesList

# struct Admin
_0_WhatsTheWord.referenceClasses.Admin = omniORB.newEmptyClass()
class Admin (omniORB.StructBase):
    _NP_RepositoryId = "IDL:WhatsTheWord/referenceClasses/Admin:1.0"

    def __init__(self, adminId, username, password, waitingTime, gameTime):
        self.adminId = adminId
        self.username = username
        self.password = password
        self.waitingTime = waitingTime
        self.gameTime = gameTime

_0_WhatsTheWord.referenceClasses.Admin = Admin
_0_WhatsTheWord.referenceClasses._d_Admin  = (omniORB.tcInternal.tv_struct, Admin, Admin._NP_RepositoryId, "Admin", "adminId", omniORB.tcInternal.tv_long, "username", (omniORB.tcInternal.tv_string,0), "password", (omniORB.tcInternal.tv_string,0), "waitingTime", omniORB.tcInternal.tv_long, "gameTime", omniORB.tcInternal.tv_long)
_0_WhatsTheWord.referenceClasses._tc_Admin = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.referenceClasses._d_Admin)
omniORB.registerType(Admin._NP_RepositoryId, _0_WhatsTheWord.referenceClasses._d_Admin, _0_WhatsTheWord.referenceClasses._tc_Admin)
del Admin

# struct Player
_0_WhatsTheWord.referenceClasses.Player = omniORB.newEmptyClass()
class Player (omniORB.StructBase):
    _NP_RepositoryId = "IDL:WhatsTheWord/referenceClasses/Player:1.0"

    def __init__(self, playerId, username, password, wins, noOfRoundWins, time, hasPlayed):
        self.playerId = playerId
        self.username = username
        self.password = password
        self.wins = wins
        self.noOfRoundWins = noOfRoundWins
        self.time = time
        self.hasPlayed = hasPlayed

_0_WhatsTheWord.referenceClasses.Player = Player
_0_WhatsTheWord.referenceClasses._d_Player  = (omniORB.tcInternal.tv_struct, Player, Player._NP_RepositoryId, "Player", "playerId", omniORB.tcInternal.tv_long, "username", (omniORB.tcInternal.tv_string,0), "password", (omniORB.tcInternal.tv_string,0), "wins", omniORB.tcInternal.tv_long, "noOfRoundWins", omniORB.tcInternal.tv_long, "time", omniORB.tcInternal.tv_long, "hasPlayed", omniORB.tcInternal.tv_boolean)
_0_WhatsTheWord.referenceClasses._tc_Player = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.referenceClasses._d_Player)
omniORB.registerType(Player._NP_RepositoryId, _0_WhatsTheWord.referenceClasses._d_Player, _0_WhatsTheWord.referenceClasses._tc_Player)
del Player

# struct Leaderboard
_0_WhatsTheWord.referenceClasses.Leaderboard = omniORB.newEmptyClass()
class Leaderboard (omniORB.StructBase):
    _NP_RepositoryId = "IDL:WhatsTheWord/referenceClasses/Leaderboard:1.0"

    def __init__(self, players):
        self.players = players

_0_WhatsTheWord.referenceClasses.Leaderboard = Leaderboard
_0_WhatsTheWord.referenceClasses._d_Leaderboard  = (omniORB.tcInternal.tv_struct, Leaderboard, Leaderboard._NP_RepositoryId, "Leaderboard", "players", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:WhatsTheWord/referenceClasses/Player:1.0"], 0))
_0_WhatsTheWord.referenceClasses._tc_Leaderboard = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.referenceClasses._d_Leaderboard)
omniORB.registerType(Leaderboard._NP_RepositoryId, _0_WhatsTheWord.referenceClasses._d_Leaderboard, _0_WhatsTheWord.referenceClasses._tc_Leaderboard)
del Leaderboard

# struct GameLobby
_0_WhatsTheWord.referenceClasses.GameLobby = omniORB.newEmptyClass()
class GameLobby (omniORB.StructBase):
    _NP_RepositoryId = "IDL:WhatsTheWord/referenceClasses/GameLobby:1.0"

    def __init__(self, gameId, players, waitingTime, gameTime, word, winner):
        self.gameId = gameId
        self.players = players
        self.waitingTime = waitingTime
        self.gameTime = gameTime
        self.word = word
        self.winner = winner

_0_WhatsTheWord.referenceClasses.GameLobby = GameLobby
_0_WhatsTheWord.referenceClasses._d_GameLobby  = (omniORB.tcInternal.tv_struct, GameLobby, GameLobby._NP_RepositoryId, "GameLobby", "gameId", omniORB.tcInternal.tv_long, "players", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:WhatsTheWord/referenceClasses/Player:1.0"], 0), "waitingTime", omniORB.tcInternal.tv_long, "gameTime", omniORB.tcInternal.tv_long, "word", (omniORB.tcInternal.tv_string,0), "winner", omniORB.typeMapping["IDL:WhatsTheWord/referenceClasses/Player:1.0"])
_0_WhatsTheWord.referenceClasses._tc_GameLobby = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.referenceClasses._d_GameLobby)
omniORB.registerType(GameLobby._NP_RepositoryId, _0_WhatsTheWord.referenceClasses._d_GameLobby, _0_WhatsTheWord.referenceClasses._tc_GameLobby)
del GameLobby

#
# End of module "WhatsTheWord.referenceClasses"
#
__name__ = "WhatsTheWord"


#
# Start of module "WhatsTheWord.game_logic"
#
__name__ = "WhatsTheWord.game_logic"
_0_WhatsTheWord.game_logic = omniORB.openModule("WhatsTheWord.game_logic", r"WhatsTheWord.idl")
_0_WhatsTheWord__POA.game_logic = omniORB.openModule("WhatsTheWord__POA.game_logic", r"WhatsTheWord.idl")


# interface Game
_0_WhatsTheWord.game_logic._d_Game = (omniORB.tcInternal.tv_objref, "IDL:WhatsTheWord/game_logic/Game:1.0", "Game")
omniORB.typeMapping["IDL:WhatsTheWord/game_logic/Game:1.0"] = _0_WhatsTheWord.game_logic._d_Game
_0_WhatsTheWord.game_logic.Game = omniORB.newEmptyClass()
class Game :
    _NP_RepositoryId = _0_WhatsTheWord.game_logic._d_Game[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WhatsTheWord.game_logic.Game = Game
_0_WhatsTheWord.game_logic._tc_Game = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.game_logic._d_Game)
omniORB.registerType(Game._NP_RepositoryId, _0_WhatsTheWord.game_logic._d_Game, _0_WhatsTheWord.game_logic._tc_Game)

# Game operations and attributes
Game._d_sendLetter = ((omniORB.tcInternal.tv_char, ), (), None)
Game._d_sendTime = ((omniORB.typeMapping["IDL:WhatsTheWord/referenceClasses/Player:1.0"], ), (), None)

# Game object reference
class _objref_Game (CORBA.Object):
    _NP_RepositoryId = Game._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def sendLetter(self, *args):
        return self._obj.invoke("sendLetter", _0_WhatsTheWord.game_logic.Game._d_sendLetter, args)

    def sendTime(self, *args):
        return self._obj.invoke("sendTime", _0_WhatsTheWord.game_logic.Game._d_sendTime, args)

omniORB.registerObjref(Game._NP_RepositoryId, _objref_Game)
_0_WhatsTheWord.game_logic._objref_Game = _objref_Game
del Game, _objref_Game

# Game skeleton
__name__ = "WhatsTheWord__POA.game_logic"
class Game (PortableServer.Servant):
    _NP_RepositoryId = _0_WhatsTheWord.game_logic.Game._NP_RepositoryId


    _omni_op_d = {"sendLetter": _0_WhatsTheWord.game_logic.Game._d_sendLetter, "sendTime": _0_WhatsTheWord.game_logic.Game._d_sendTime}

Game._omni_skeleton = Game
_0_WhatsTheWord__POA.game_logic.Game = Game
omniORB.registerSkeleton(Game._NP_RepositoryId, Game)
del Game
__name__ = "WhatsTheWord.game_logic"

#
# End of module "WhatsTheWord.game_logic"
#
__name__ = "WhatsTheWord"


#
# Start of module "WhatsTheWord.client"
#
__name__ = "WhatsTheWord.client"
_0_WhatsTheWord.client = omniORB.openModule("WhatsTheWord.client", r"WhatsTheWord.idl")
_0_WhatsTheWord__POA.client = omniORB.openModule("WhatsTheWord__POA.client", r"WhatsTheWord.idl")


# interface ClientCallback
_0_WhatsTheWord.client._d_ClientCallback = (omniORB.tcInternal.tv_objref, "IDL:WhatsTheWord/client/ClientCallback:1.0", "ClientCallback")
omniORB.typeMapping["IDL:WhatsTheWord/client/ClientCallback:1.0"] = _0_WhatsTheWord.client._d_ClientCallback
_0_WhatsTheWord.client.ClientCallback = omniORB.newEmptyClass()
class ClientCallback :
    _NP_RepositoryId = _0_WhatsTheWord.client._d_ClientCallback[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WhatsTheWord.client.ClientCallback = ClientCallback
_0_WhatsTheWord.client._tc_ClientCallback = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.client._d_ClientCallback)
omniORB.registerType(ClientCallback._NP_RepositoryId, _0_WhatsTheWord.client._d_ClientCallback, _0_WhatsTheWord.client._tc_ClientCallback)

# ClientCallback operations and attributes
ClientCallback._d_notify = ((omniORB.typeMapping["IDL:WhatsTheWord/referenceClasses/ValuesList:1.0"], ), (), None)

# ClientCallback object reference
class _objref_ClientCallback (CORBA.Object):
    _NP_RepositoryId = ClientCallback._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def notify(self, *args):
        return self._obj.invoke("notify", _0_WhatsTheWord.client.ClientCallback._d_notify, args)

omniORB.registerObjref(ClientCallback._NP_RepositoryId, _objref_ClientCallback)
_0_WhatsTheWord.client._objref_ClientCallback = _objref_ClientCallback
del ClientCallback, _objref_ClientCallback

# ClientCallback skeleton
__name__ = "WhatsTheWord__POA.client"
class ClientCallback (PortableServer.Servant):
    _NP_RepositoryId = _0_WhatsTheWord.client.ClientCallback._NP_RepositoryId


    _omni_op_d = {"notify": _0_WhatsTheWord.client.ClientCallback._d_notify}

ClientCallback._omni_skeleton = ClientCallback
_0_WhatsTheWord__POA.client.ClientCallback = ClientCallback
omniORB.registerSkeleton(ClientCallback._NP_RepositoryId, ClientCallback)
del ClientCallback
__name__ = "WhatsTheWord.client"

#
# Start of module "WhatsTheWord.client.admin"
#
__name__ = "WhatsTheWord.client.admin"
_0_WhatsTheWord.client.admin = omniORB.openModule("WhatsTheWord.client.admin", r"WhatsTheWord.idl")
_0_WhatsTheWord__POA.client.admin = omniORB.openModule("WhatsTheWord__POA.client.admin", r"WhatsTheWord.idl")


# enum AdminRequestType
_0_WhatsTheWord.client.admin.ADMIN_LOGIN = omniORB.EnumItem("ADMIN_LOGIN", 0)
_0_WhatsTheWord.client.admin.ADMIN_LOGOUT = omniORB.EnumItem("ADMIN_LOGOUT", 1)
_0_WhatsTheWord.client.admin.CREATE_NEW_PLAYER = omniORB.EnumItem("CREATE_NEW_PLAYER", 2)
_0_WhatsTheWord.client.admin.GET_PLAYER_DETAILS = omniORB.EnumItem("GET_PLAYER_DETAILS", 3)
_0_WhatsTheWord.client.admin.UPDATE_PLAYER_DETAILS = omniORB.EnumItem("UPDATE_PLAYER_DETAILS", 4)
_0_WhatsTheWord.client.admin.DELETE_PLAYER = omniORB.EnumItem("DELETE_PLAYER", 5)
_0_WhatsTheWord.client.admin.SEARCH_PLAYER = omniORB.EnumItem("SEARCH_PLAYER", 6)
_0_WhatsTheWord.client.admin.SET_LOBBY_WAITING_TIME = omniORB.EnumItem("SET_LOBBY_WAITING_TIME", 7)
_0_WhatsTheWord.client.admin.SET_ROUND_TIME = omniORB.EnumItem("SET_ROUND_TIME", 8)
_0_WhatsTheWord.client.admin.AdminRequestType = omniORB.Enum("IDL:WhatsTheWord/client/admin/AdminRequestType:1.0", (_0_WhatsTheWord.client.admin.ADMIN_LOGIN, _0_WhatsTheWord.client.admin.ADMIN_LOGOUT, _0_WhatsTheWord.client.admin.CREATE_NEW_PLAYER, _0_WhatsTheWord.client.admin.GET_PLAYER_DETAILS, _0_WhatsTheWord.client.admin.UPDATE_PLAYER_DETAILS, _0_WhatsTheWord.client.admin.DELETE_PLAYER, _0_WhatsTheWord.client.admin.SEARCH_PLAYER, _0_WhatsTheWord.client.admin.SET_LOBBY_WAITING_TIME, _0_WhatsTheWord.client.admin.SET_ROUND_TIME,))

_0_WhatsTheWord.client.admin._d_AdminRequestType  = (omniORB.tcInternal.tv_enum, _0_WhatsTheWord.client.admin.AdminRequestType._NP_RepositoryId, "AdminRequestType", _0_WhatsTheWord.client.admin.AdminRequestType._items)
_0_WhatsTheWord.client.admin._tc_AdminRequestType = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.client.admin._d_AdminRequestType)
omniORB.registerType(_0_WhatsTheWord.client.admin.AdminRequestType._NP_RepositoryId, _0_WhatsTheWord.client.admin._d_AdminRequestType, _0_WhatsTheWord.client.admin._tc_AdminRequestType)

# interface AdminService
_0_WhatsTheWord.client.admin._d_AdminService = (omniORB.tcInternal.tv_objref, "IDL:WhatsTheWord/client/admin/AdminService:1.0", "AdminService")
omniORB.typeMapping["IDL:WhatsTheWord/client/admin/AdminService:1.0"] = _0_WhatsTheWord.client.admin._d_AdminService
_0_WhatsTheWord.client.admin.AdminService = omniORB.newEmptyClass()
class AdminService :
    _NP_RepositoryId = _0_WhatsTheWord.client.admin._d_AdminService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WhatsTheWord.client.admin.AdminService = AdminService
_0_WhatsTheWord.client.admin._tc_AdminService = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.client.admin._d_AdminService)
omniORB.registerType(AdminService._NP_RepositoryId, _0_WhatsTheWord.client.admin._d_AdminService, _0_WhatsTheWord.client.admin._tc_AdminService)

# AdminService operations and attributes
AdminService._d_request = ((omniORB.typeMapping["IDL:WhatsTheWord/client/admin/AdminRequestType:1.0"], omniORB.typeMapping["IDL:WhatsTheWord/referenceClasses/Admin:1.0"], omniORB.typeMapping["IDL:WhatsTheWord/client/ClientCallback:1.0"]), (), None)

# AdminService object reference
class _objref_AdminService (CORBA.Object):
    _NP_RepositoryId = AdminService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def request(self, *args):
        return self._obj.invoke("request", _0_WhatsTheWord.client.admin.AdminService._d_request, args)

omniORB.registerObjref(AdminService._NP_RepositoryId, _objref_AdminService)
_0_WhatsTheWord.client.admin._objref_AdminService = _objref_AdminService
del AdminService, _objref_AdminService

# AdminService skeleton
__name__ = "WhatsTheWord__POA.client.admin"
class AdminService (PortableServer.Servant):
    _NP_RepositoryId = _0_WhatsTheWord.client.admin.AdminService._NP_RepositoryId


    _omni_op_d = {"request": _0_WhatsTheWord.client.admin.AdminService._d_request}

AdminService._omni_skeleton = AdminService
_0_WhatsTheWord__POA.client.admin.AdminService = AdminService
omniORB.registerSkeleton(AdminService._NP_RepositoryId, AdminService)
del AdminService
__name__ = "WhatsTheWord.client.admin"

#
# End of module "WhatsTheWord.client.admin"
#
__name__ = "WhatsTheWord.client"


#
# Start of module "WhatsTheWord.client.player"
#
__name__ = "WhatsTheWord.client.player"
_0_WhatsTheWord.client.player = omniORB.openModule("WhatsTheWord.client.player", r"WhatsTheWord.idl")
_0_WhatsTheWord__POA.client.player = omniORB.openModule("WhatsTheWord__POA.client.player", r"WhatsTheWord.idl")


# enum PlayerRequestType
_0_WhatsTheWord.client.player.REGISTER = omniORB.EnumItem("REGISTER", 0)
_0_WhatsTheWord.client.player.LOGIN = omniORB.EnumItem("LOGIN", 1)
_0_WhatsTheWord.client.player.START_GAME = omniORB.EnumItem("START_GAME", 2)
_0_WhatsTheWord.client.player.GET_LEADERBOARD = omniORB.EnumItem("GET_LEADERBOARD", 3)
_0_WhatsTheWord.client.player.LOGOUT = omniORB.EnumItem("LOGOUT", 4)
_0_WhatsTheWord.client.player.PlayerRequestType = omniORB.Enum("IDL:WhatsTheWord/client/player/PlayerRequestType:1.0", (_0_WhatsTheWord.client.player.REGISTER, _0_WhatsTheWord.client.player.LOGIN, _0_WhatsTheWord.client.player.START_GAME, _0_WhatsTheWord.client.player.GET_LEADERBOARD, _0_WhatsTheWord.client.player.LOGOUT,))

_0_WhatsTheWord.client.player._d_PlayerRequestType  = (omniORB.tcInternal.tv_enum, _0_WhatsTheWord.client.player.PlayerRequestType._NP_RepositoryId, "PlayerRequestType", _0_WhatsTheWord.client.player.PlayerRequestType._items)
_0_WhatsTheWord.client.player._tc_PlayerRequestType = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.client.player._d_PlayerRequestType)
omniORB.registerType(_0_WhatsTheWord.client.player.PlayerRequestType._NP_RepositoryId, _0_WhatsTheWord.client.player._d_PlayerRequestType, _0_WhatsTheWord.client.player._tc_PlayerRequestType)

# interface PlayerService
_0_WhatsTheWord.client.player._d_PlayerService = (omniORB.tcInternal.tv_objref, "IDL:WhatsTheWord/client/player/PlayerService:1.0", "PlayerService")
omniORB.typeMapping["IDL:WhatsTheWord/client/player/PlayerService:1.0"] = _0_WhatsTheWord.client.player._d_PlayerService
_0_WhatsTheWord.client.player.PlayerService = omniORB.newEmptyClass()
class PlayerService :
    _NP_RepositoryId = _0_WhatsTheWord.client.player._d_PlayerService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WhatsTheWord.client.player.PlayerService = PlayerService
_0_WhatsTheWord.client.player._tc_PlayerService = omniORB.tcInternal.createTypeCode(_0_WhatsTheWord.client.player._d_PlayerService)
omniORB.registerType(PlayerService._NP_RepositoryId, _0_WhatsTheWord.client.player._d_PlayerService, _0_WhatsTheWord.client.player._tc_PlayerService)

# PlayerService operations and attributes
PlayerService._d_request = ((omniORB.typeMapping["IDL:WhatsTheWord/client/player/PlayerRequestType:1.0"], omniORB.typeMapping["IDL:WhatsTheWord/referenceClasses/Player:1.0"], omniORB.typeMapping["IDL:WhatsTheWord/client/ClientCallback:1.0"]), (), None)

# PlayerService object reference
class _objref_PlayerService (CORBA.Object):
    _NP_RepositoryId = PlayerService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def request(self, *args):
        return self._obj.invoke("request", _0_WhatsTheWord.client.player.PlayerService._d_request, args)

omniORB.registerObjref(PlayerService._NP_RepositoryId, _objref_PlayerService)
_0_WhatsTheWord.client.player._objref_PlayerService = _objref_PlayerService
del PlayerService, _objref_PlayerService

# PlayerService skeleton
__name__ = "WhatsTheWord__POA.client.player"
class PlayerService (PortableServer.Servant):
    _NP_RepositoryId = _0_WhatsTheWord.client.player.PlayerService._NP_RepositoryId


    _omni_op_d = {"request": _0_WhatsTheWord.client.player.PlayerService._d_request}

PlayerService._omni_skeleton = PlayerService
_0_WhatsTheWord__POA.client.player.PlayerService = PlayerService
omniORB.registerSkeleton(PlayerService._NP_RepositoryId, PlayerService)
del PlayerService
__name__ = "WhatsTheWord.client.player"

#
# End of module "WhatsTheWord.client.player"
#
__name__ = "WhatsTheWord.client"


#
# End of module "WhatsTheWord.client"
#
__name__ = "WhatsTheWord"


#
# End of module "WhatsTheWord"
#
__name__ = "WhatsTheWord_idl"

_exported_modules = ( "WhatsTheWord", "WhatsTheWord.client", "WhatsTheWord.client.admin", "WhatsTheWord.client.player", "WhatsTheWord.game_logic", "WhatsTheWord.referenceClasses")

# The end.
